version: '3'

services:
  backend-api:
    image: backend-three-tier
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    networks:
      - multi-tier-docker
    depends_on:
      - mongo
  frontend-client:
    image: 'frontend-three-tier'
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - multi-tier-docker
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-api
  mongo:
    image: mongo
    networks:
      - multi-tier-docker
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

networks:
  multi-tier-docker:
    driver: bridge

volumes:
  mongodb:
  mongodb_config: